config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  root 'static_pages#home'

  get 'static_pages/home'

  get 'static_pages/secret', as: 'secret'

  get 'users/new', as: 'new_user'

  get 'users/create'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

get '/login', to: 'sessions#new'
post '/login', to: 'sessions#new'
delete '/logout', to: 'sessions#new'
resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  	
  	def new
  	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			log_in user
			redirect_to secret_path # créer page secrete, c'est la rediretion directe après le log in
		else 
			flash.now[:danger] = 'Invalid email/password'
			render 'new'

		end
	end

	def destroy
		log_out
		redirect_to root_url
	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])

  def create
  	@user = User.new(user_params)
  	if @user.save
  		log_in @user
  		flash[:success] = 'Bravo'
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  @user = User.find(params[:id]) 
  end

  def update
  end

  def destroy
  end

  private

  	def user_params
  		params.require(:user).permit(:email, :password_confirmation)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user) # lorsque l'utilisateur quitte la fenêtre, la session est automatiquement fermée
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])

	end

	def logged_in?
		current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end


end

app/helpers/static_pages.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="http://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-css-1.2.8.min.css"/>
    <title>Secret</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
                                              >
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "The secret ...", '#', id: "logo" %>
        <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil", root_path %></li>
        <% if logged_in? %>
         
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Compte <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1> Connais-tu déjà le secret de l'univers... ?</h1>

<% if logged_in? %>
  <%= link_to "Je veux découvrir le secret", secret_path, class: "btn btn-lg btn-primary" %>
  <% else %>
   <%= link_to "Je veux découvrir le secret", new_user_path, class: "btn btn-lg btn-primary" %>
   <% end %>
</div>

app/views/static_pages/secret.html.erb
<div class="center jumbotron">

<% if logged_in? %>
  <h1> THP contrôle le monde de 42 façons </h1>

  <% else %>
  <h3> Pour en savoir plus....inscris-toi </h3>
<%= link_to "Je suis faible et je veux me connecter", login_path %>
  <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Inscription</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Créer le compte", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user == current_user %>

<h2>Connecté avec l'adresse <%= @user.email %> </h2>

<% else %>

<h2> Essaies encore </h2>

<% end %>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>